/** Game shell & M1 screen strings (DESIGN §6 — tutoiement, lore voice). */
export const UI_FR = {
  nav: {
    map: 'Carte',
    bastion: 'Bastion',
    hero: 'Héros',
    raid: 'Raid',
  },
  status: {
    hp: 'PV',
    stamina: 'Endurance',
    ashCrowns: 'écus',
    emberFragments: 'fragments',
    gloryMarks: 'gloire',
    level: 'niv.',
    notifLabel: 'Notifications',
    settingsLabel: 'Réglages',
  },
  queue: {
    empty: 'Aucune action en cours — la flammèche attend.',
    move: 'Déplacement',
    rest: 'Repos à l’autel',
    search: 'Fouille',
    queued: 'en file',
    title: 'File d’actions',
    current: 'En cours',
    waiting: 'En attente',
    cancel: 'Annuler',
    close: 'Fermer',
    openHint: 'Voir la file',
  },
  map: {
    mistLevelLabel: 'Brume niveau',
    pickHexTitle: 'Choisis un hexagone',
    pickHexHint: 'Touche une case adjacente pour voir le coût du déplacement.',
    fogTitle: 'Brume opaque',
    fogHint: 'Personne n’a encore cartographié cette zone. Approche-toi pour la révéler.',
    hereSuffix: 'Tu es ici.',
    tooFar: 'Trop loin : avance de case en case (ou empile jusqu’à 3 actions).',
    mistTax: 'La Brume alourdit le pas.',
    staminaCost: 'endurance',
    moveAction: 'Se mettre en route',
    restAction: 'Se reposer (30 min · +75 ⚡)',
    queuedFromHint: 'Coût depuis la fin de ta file d’actions.',
    cancelAction: 'Annuler',
    terrainsTitle: 'Terrains',
    legendTitle: 'Légende',
    legendYou: 'Vous',
    legendPoi: 'Point d’intérêt',
    legendEmber: 'Braise',
    legendGuardianLocked: 'Gardien (verrouillé)',
    legendMist: 'Brume',
    terrains: {
      plain: 'Plaine',
      forest: 'Forêt',
      hill: 'Colline',
      marsh: 'Marais',
      ruins: 'Ruines',
      ash_road: 'Route de cendre',
      ford: 'Gué',
      shrine: 'Autel',
    } as Record<string, string>,
  },
  creation: {
    eyebrow: 'La Salle des Cendres',
    title: 'Éveille ton Ravivé',
    intro:
      'La dernière Braise a refusé de te laisser partir. Choisis le nom qu’on gravera sur ta lanterne, et la voie que ta flammèche suivra.',
    nameLabel: 'Nom du Ravivé',
    namePlaceholder: '3 à 24 caractères',
    classLabel: 'Choisis ta voie',
    submit: 'Rejoindre le bastion',
    classes: {
      blade: {
        name: 'La Lame',
        tagline: 'Encaisse et protège. Les remparts marchent avec elle.',
      },
      arcanist: {
        name: 'L’Arcaniste',
        tagline: 'La cendrelumière obéit à qui sait lire les Archives.',
      },
      scout: {
        name: 'L’Éclaireur',
        tagline: 'Les Routes de Cendre n’ont pas de secret pour lui.',
      },
      cantor: {
        name: 'Le Chantre',
        tagline: 'Sa voix ravive les Braises — et ceux qui marchent avec lui.',
      },
    } as Record<string, { name: string; tagline: string }>,
  },
  placeholders: {
    raid: 'Les Gardiens dorment encore. Reviens quand le Glas sonnera.',
  },
  combat: {
    attack: 'Attaque',
    attackSub: 'fiable',
    skillSub: (cd: number) => (cd > 0 ? `recharge : ${cd} t` : '×1,3 · recharge 2 t'),
    itemLabel: 'Potion de cendre',
    itemSub: (left: number) => `+30 PV · reste ${left}`,
    flee: 'Fuir',
    fleeSub: 'tenter sa chance',
    turnLabel: 'tour',
    victory: 'Victoire !',
    defeat: 'Ta flammèche vacille…',
    fled: 'Tu t’es fondu dans la Brume.',
    rewardsXp: 'XP',
    rewardsCrowns: 'écus',
    lootLostNote: 'Sac plein — une partie du butin est restée dans la Brume.',
    close: 'Reprendre la route',
    skillNames: {
      'blade.steel.1': 'Frappe lourde',
      'arcanist.ashlight.1': 'Trait de cendre',
      'scout.hunt.1': 'Tir précis',
      'cantor.verse.2': 'Litanie',
    } as Record<string, string>,
  },
  hero: {
    statLabels: { str: 'FOR', dex: 'ADR', wil: 'VOL', vit: 'VIT', fer: 'FER' } as Record<
      string,
      string
    >,
    pointsToAllocate: (n: number) => `${n} point${n > 1 ? 's' : ''} d’attribut à répartir`,
    penaltyLabel: 'Flammèche vacillante',
    penaltyHint: 'Tes stats sont réduites de 20 % encore',
    equipmentTitle: 'Équipement & sac',
    capacityLabel: (used: number, cap: number) => `${used} / ${cap} emplacements`,
    equip: 'Équiper',
    unequip: 'Retirer',
    use: 'Utiliser',
    equippedTag: 'équipé',
    xpLabel: 'XP',
  },
  bastion: {
    enter: 'Entrer',
    back: '← Retour',
  },
  quests: {
    boardTitle: 'Tableau de Mira',
    boardHint: '« On ne meurt qu’une fois par jour, c’est le règlement. »',
    accept: 'Accepter',
    stateActive: 'En cours',
    stateDone: 'Accomplie',
    stateAvailable: 'Disponible',
    killProgress: (done: number, total: number) => `${done} / ${total}`,
    startFight: 'Affronter (⚡15)',
  },
  mapExtra: {
    searchAction: 'Fouiller (⚡10 · 5 min)',
    combatWaiting: 'Un Brumeux te barre la route !',
  },
  errors: {
    loadFailed: 'Le bastion est injoignable — réessaie dans un instant.',
  },
  chat: {
    title: 'Le Bastion murmure',
    channelGlobal: 'Global',
    channelRegion: 'Région',
    placeholder: 'Écris un mot…',
    send: 'Envoyer',
    empty: 'Rien à lire pour l’instant. Sois le premier.',
    throttled: 'Doucement — laisse ta flammèche reprendre son souffle.',
    toggleLabel: 'Discussion',
  },
  project: {
    title: 'Le Beffroi du Grand Cairn',
    hint: 'Reconstruisez le beffroi pour sonner le Glas.',
    contributorCount: (n: number) => `${n} Ravivé${n > 1 ? 's' : ''} ont posé une pierre`,
    qtyLabel: 'Quantité',
    contribute: (resourceName: string, qty: number) => `Livrer ${qty} ${resourceName} (⚡5)`,
    completed: 'Le Glas a sonné.',
    myContribution: 'Ta pierre à l’édifice',
  },
  market: {
    title: 'L’Hôtel des ventes',
    listingsTab: 'Annonces',
    sellTab: 'Vendre',
    itemLabel: 'Objet',
    qtyLabel: 'Quantité',
    priceLabel: 'Prix unitaire (◉)',
    listAction: 'Mettre en vente',
    buyAction: (qty: number, total: number) => `Acheter ${qty} (◉${total})`,
    cancelAction: 'Annuler l’annonce',
    ownListing: 'Ton annonce',
    empty: 'L’hôtel est vide pour l’instant.',
    sellerLabel: 'Vendeur',
  },
  skillsTree: {
    tabPersonnage: 'Personnage',
    tabSkills: 'Compétences',
    pointsAvailable: (n: number) => `${n} point${n > 1 ? 's' : ''} de compétence`,
    fragmentsAvailable: (n: number) => `${n} fragment${n > 1 ? 's' : ''} de braise`,
    learn: 'Apprendre',
    equip: 'Équiper',
    unequip: 'Retirer',
    equippedTag: 'équipée',
    slotLabel: (n: 1 | 2) => `Emplacement ${n}`,
    branches: {
      bulwark: 'Rempart',
      steel: 'Fer',
      veteran: 'Vétéran',
      ashlight: 'Cendrelumière',
      veil: 'Voile',
      scholar: 'Savant',
      hunt: 'Traque',
      travel: 'Voyage',
      shadow: 'Ombre',
      hymn: 'Hymne',
      ember: 'Braise',
      verse: 'Verbe',
    } as Record<string, string>,
    costFragments: (n: number) => `+ ${n} ✦`,
    costPoint: '1 pt',
  },
  repair: {
    action: 'Réparer',
    cost: (crowns: number) => `Réparer (◉${crowns})`,
    full: 'En parfait état',
    durabilityLabel: (current: number, max: number) => `${current} / ${max}`,
  },
} as const;
