/** Game shell & M1 screen strings (DESIGN §6 — tutoiement, lore voice). */
export const UI_FR = {
  nav: {
    map: 'Carte',
    bastion: 'Bastion',
    hero: 'Héros',
    raid: 'Raid',
  },
  status: {
    hp: 'PV',
    stamina: 'Endurance',
    ashCrowns: 'écus',
    emberFragments: 'fragments',
    gloryMarks: 'gloire',
    level: 'niv.',
  },
  queue: {
    empty: 'Aucune action en cours — la flammèche attend.',
    move: 'Déplacement',
    rest: 'Repos à l’autel',
    queued: 'en file',
  },
  map: {
    mistLevelLabel: 'Brume niveau',
    pickHexTitle: 'Choisis un hexagone',
    pickHexHint: 'Touche une case adjacente pour voir le coût du déplacement.',
    fogTitle: 'Brume opaque',
    fogHint: 'Personne n’a encore cartographié cette zone. Approche-toi pour la révéler.',
    hereSuffix: 'Tu es ici.',
    tooFar: 'Trop loin : avance de case en case (ou empile jusqu’à 3 actions).',
    mistTax: 'La Brume alourdit le pas.',
    staminaCost: 'endurance',
    moveAction: 'Se mettre en route',
    restAction: 'Se reposer (30 min · +75 ⚡)',
    queuedFromHint: 'Coût depuis la fin de ta file d’actions.',
    cancelAction: 'Annuler',
    terrains: {
      plain: 'Plaine',
      forest: 'Forêt',
      hill: 'Colline',
      marsh: 'Marais',
      ruins: 'Ruines',
      ash_road: 'Route de cendre',
      ford: 'Gué',
      shrine: 'Autel',
    } as Record<string, string>,
  },
  creation: {
    eyebrow: 'La Salle des Cendres',
    title: 'Éveille ton Ravivé',
    intro:
      'La dernière Braise a refusé de te laisser partir. Choisis le nom qu’on gravera sur ta lanterne, et la voie que ta flammèche suivra.',
    nameLabel: 'Nom du Ravivé',
    namePlaceholder: '3 à 24 caractères',
    classLabel: 'Choisis ta voie',
    submit: 'Rejoindre le bastion',
    classes: {
      blade: {
        name: 'La Lame',
        tagline: 'Encaisse et protège. Les remparts marchent avec elle.',
      },
      arcanist: {
        name: 'L’Arcaniste',
        tagline: 'La cendrelumière obéit à qui sait lire les Archives.',
      },
      scout: {
        name: 'L’Éclaireur',
        tagline: 'Les Routes de Cendre n’ont pas de secret pour lui.',
      },
      cantor: {
        name: 'Le Chantre',
        tagline: 'Sa voix ravive les Braises — et ceux qui marchent avec lui.',
      },
    } as Record<string, { name: string; tagline: string }>,
  },
  placeholders: {
    raid: 'Les Gardiens dorment encore. Reviens quand le Glas sonnera.',
  },
  combat: {
    attack: 'Attaque',
    attackSub: 'fiable',
    skillSub: (cd: number) => (cd > 0 ? `recharge : ${cd} t` : '×1,3 · recharge 2 t'),
    itemLabel: 'Potion de cendre',
    itemSub: (left: number) => `+30 PV · reste ${left}`,
    flee: 'Fuir',
    fleeSub: 'tenter sa chance',
    turnLabel: 'tour',
    victory: 'Victoire !',
    defeat: 'Ta flammèche vacille…',
    fled: 'Tu t’es fondu dans la Brume.',
    rewardsXp: 'XP',
    rewardsCrowns: 'écus',
    lootLostNote: 'Sac plein — une partie du butin est restée dans la Brume.',
    close: 'Reprendre la route',
    skillNames: {
      'blade.steel.1': 'Frappe lourde',
      'arcanist.ashlight.1': 'Trait de cendre',
      'scout.hunt.1': 'Tir précis',
      'cantor.verse.2': 'Litanie',
    } as Record<string, string>,
  },
  hero: {
    statLabels: { str: 'FOR', dex: 'ADR', wil: 'VOL', vit: 'VIT', fer: 'FER' } as Record<string, string>,
    pointsToAllocate: (n: number) => `${n} point${n > 1 ? 's' : ''} d’attribut à répartir`,
    penaltyLabel: 'Flammèche vacillante',
    penaltyHint: 'Tes stats sont réduites de 20 % encore',
    equipmentTitle: 'Équipement & sac',
    capacityLabel: (used: number, cap: number) => `${used} / ${cap} emplacements`,
    equip: 'Équiper',
    unequip: 'Retirer',
    use: 'Utiliser',
    equippedTag: 'équipé',
    xpLabel: 'XP',
  },
  quests: {
    boardTitle: 'Tableau de Mira',
    boardHint: '« On ne meurt qu’une fois par jour, c’est le règlement. »',
    accept: 'Accepter',
    stateActive: 'En cours',
    stateDone: 'Accomplie',
    stateAvailable: 'Disponible',
    killProgress: (done: number, total: number) => `${done} / ${total}`,
    startFight: 'Affronter (⚡15)',
  },
  mapExtra: {
    searchAction: 'Fouiller (⚡10 · 5 min)',
    combatWaiting: 'Un Brumeux te barre la route !',
  },
  errors: {
    loadFailed: 'Le bastion est injoignable — réessaie dans un instant.',
  },
} as const;
